#!/bin/bash 

# Build on RPI target
host=192.168.100.103
proj=SRF02

# Pack sources locally
tar --exclude build --exclude build_remote -czf /tmp/code.tgz . 

# copy archive to target
scp /tmp/code.tgz ${host}:/tmp

# unpcak and build
ssh ${host} -x "mkdir -p ${proj}/build &&                      \
                (cd ${proj} && tar xzvf /tmp/code.tgz  &&      \
                (cd build   && cmake ../CMakeLists.txt && make  \
              ))"