#!/bin/bash 

# Build on RPI target
host=192.168.100.101
proj=SRF02


# Pack sources locally
echo -n "-- Create archive"
tar --exclude build --exclude build_remote --exclude-vcs --no-xattrs --no-mac-metadata -czf /tmp/code.tgz . 
echo " done"

# copy archive to target
echo -n "-- Transfer files to build client (${host})"
scp -q /tmp/code.tgz ${host}:/tmp
echo " done"

# unpack and build
ssh ${host} -x "mkdir -p ${proj}/build &&                      \
                (cd ${proj} && tar xzf /tmp/code.tgz  &&      \
                (cd build   && cmake ../CMakeLists.txt && make  \
              ))"